# Generated by Django 2.0.3 on 2018-03-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180313_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='value',
            field=models.CharField(default='', max_length=200),
        ),
    ]
