# Generated by Django 2.0.3 on 2018-03-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_ping'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='notify_to',
            field=models.TextField(default='{}'),
        ),
    ]
