# Generated by Django 2.0.3 on 2018-03-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_service_notify_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='grace',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('running', 'running'), ('stoped', 'stoped')], default='running', max_length=20),
        ),
    ]
